databases:
  - name: registro-civil-db
    plan: free
    databaseName: registro_civil
    user: registro_civil

services:
  - type: web
    name: registro-civil-03
    runtime: python
    plan: free
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --no-input && python manage.py migrate --no-input && python manage.py seed_initial_data"
    startCommand: "gunicorn core_rc.wsgi:application --bind 0.0.0.0:$PORT"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: registro-civil-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: PYTHON_VERSION
        value: 3.12.11
      - key: WEB_CONCURRENCY
        value: 2
