import { useState, type FormEvent } from 'react'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { Bar, BarChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import { Ban, BookOpenCheck, FileClock, Landmark, Plus, Trash2 } from 'lucide-react'
import { Button } from '@/components/ui/button'
import { Card, CardDescription, CardTitle } from '@/components/ui/card'
import { Alert, EmptyState, LoadingState } from '@/components/ui/feedback'
import { Field, Input, Select, Textarea } from '@/components/ui/field'
import { api, postJson } from '@/lib/api'
import { formatMoney } from '@/lib/utils'

export function FinancialReportPage() {
  const report = useQuery({ queryKey: ['financial-report'], queryFn: () => api<{ total: number; procedures: number; active_users: number; average_minutes: number; month: string; year: number; weekly: number[]; by_procedure: { procedure: string; quantity: number; total: number }[] }>('/citas/api/v1/reports/financial/') })
  if (report.isLoading) return <LoadingState />
  if (report.isError) return <Alert variant="error">{report.error.message}</Alert>
  const weekly = ['Lun', 'Mar', 'Mié', 'Jue', 'Vie', 'Sáb', 'Dom'].map((day, index) => ({ day, total: report.data?.weekly[index] || 0 }))
  return <section><p className="text-sm font-semibold text-primary">Finanzas</p><h1 className="mt-1 font-heading text-2xl font-semibold md:text-4xl">Reporte de ingresos</h1><p className="mt-3 text-warm-500">{report.data?.month} de {report.data?.year}</p><div className="mt-8 grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Card><CardDescription>Ingresos</CardDescription><p className="mt-2 font-heading text-2xl font-semibold">{formatMoney(report.data?.total || 0)}</p></Card><Card><CardDescription>Trámites cobrados</CardDescription><p className="mt-2 font-heading text-2xl font-semibold">{report.data?.procedures}</p></Card><Card><CardDescription>Usuarios activos</CardDescription><p className="mt-2 font-heading text-2xl font-semibold">{report.data?.active_users}</p></Card><Card><CardDescription>Duración promedio</CardDescription><p className="mt-2 font-heading text-2xl font-semibold">{report.data?.average_minutes} min</p></Card></div><Card className="mt-6"><CardTitle>Atenciones por día</CardTitle><div className="mt-5 h-72"><ResponsiveContainer width="100%" height="100%"><BarChart data={weekly}><CartesianGrid strokeDasharray="3 3" /><XAxis dataKey="day" /><YAxis allowDecimals={false} /><Tooltip /><Bar dataKey="total" fill="#0B4A2B" radius={[8, 8, 0, 0]} /></BarChart></ResponsiveContainer></div></Card><Card className="mt-6"><CardTitle>Desglose por trámite</CardTitle><div className="mt-4 overflow-x-auto"><table className="w-full min-w-[560px] text-left text-sm"><thead><tr className="border-b"><th className="p-3">Trámite</th><th className="p-3">Cantidad</th><th className="p-3">Total</th></tr></thead><tbody>{report.data?.by_procedure.map((item) => <tr key={item.procedure} className="border-b"><td className="p-3">{item.procedure}</td><td className="p-3">{item.quantity}</td><td className="p-3 font-semibold">{formatMoney(item.total)}</td></tr>)}</tbody></table></div></Card></section>
}

export function AuditPage() {
  const [query, setQuery] = useState('')
  const audit = useQuery({ queryKey: ['audit', query], queryFn: () => api<{ records: { id: number; user: string; action: string; description: string; ip: string; date: string }[] }>(`/citas/api/v1/audit/?q=${encodeURIComponent(query)}`) })
  return <section><p className="text-sm font-semibold text-primary">Seguridad y trazabilidad</p><h1 className="mt-1 font-heading text-2xl font-semibold md:text-4xl">Bitácora de auditoría</h1><div className="mt-6 max-w-xl"><Field label="Buscar movimiento" htmlFor="audit-query"><Input id="audit-query" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Usuario, descripción o IP" /></Field></div>{audit.isLoading ? <LoadingState /> : !audit.data?.records.length ? <div className="mt-8"><EmptyState title="Sin movimientos" description="No se encontraron registros con los filtros actuales." /></div> : <div className="mt-8 space-y-3">{audit.data.records.map((record) => <Card key={record.id} className="flex gap-4"><FileClock className="h-7 w-7 shrink-0 text-primary" /><div><div className="flex flex-wrap gap-2"><strong>{record.user}</strong><span className="rounded-full bg-warm-100 px-2 py-0.5 text-xs">{record.action}</span></div><p className="mt-1 text-sm text-warm-700">{record.description}</p><p className="mt-2 text-xs text-warm-500">{new Date(record.date).toLocaleString('es-MX')} · {record.ip || 'IP no disponible'}</p></div></Card>)}</div>}</section>
}

export function ScheduleBlocksPage() {
  const client = useQueryClient()
  const blocks = useQuery({ queryKey: ['blocks'], queryFn: () => api<{ blocks: { id: number; date: string; time: string | null; reason: string }[] }>('/citas/api/v1/schedule-blocks/') })
  const [date, setDate] = useState(''); const [reason, setReason] = useState('')
  const create = useMutation({ mutationFn: () => postJson('/citas/api/v1/schedule-blocks/', { date, type: 'dia_completo', reason }), onSuccess: () => { setDate(''); setReason(''); client.invalidateQueries({ queryKey: ['blocks'] }) } })
  const remove = useMutation({ mutationFn: (id: number) => api(`/citas/api/v1/schedule-blocks/${id}/`, { method: 'DELETE' }), onSuccess: () => client.invalidateQueries({ queryKey: ['blocks'] }) })
  return <section><p className="text-sm font-semibold text-primary">Disponibilidad</p><h1 className="mt-1 font-heading text-2xl font-semibold md:text-4xl">Bloqueos de horarios</h1><p className="mt-3 text-warm-500">Cierra fechas no laborables para evitar nuevas citas.</p>{create.isError ? <Alert variant="error" className="mt-5">{create.error.message}</Alert> : null}<Card className="mt-8"><form className="grid gap-5 md:grid-cols-[220px_1fr_auto] md:items-end" onSubmit={(event) => { event.preventDefault(); create.mutate() }}><Field label="Fecha" htmlFor="block-date"><Input id="block-date" type="date" required value={date} onChange={(event) => setDate(event.target.value)} /></Field><Field label="Motivo" htmlFor="block-reason"><Input id="block-reason" value={reason} onChange={(event) => setReason(event.target.value)} placeholder="Ejemplo: día no laborable" /></Field><Button loading={create.isPending}><Ban className="h-6 w-6" />Bloquear día</Button></form></Card><div className="mt-6 space-y-3">{blocks.data?.blocks.map((block) => <Card key={block.id} className="flex items-center justify-between gap-4"><div><CardTitle>{block.date}{block.time ? ` · ${block.time}` : ' · Día completo'}</CardTitle><CardDescription>{block.reason || 'Sin motivo registrado'}</CardDescription></div><Button size="icon" variant="danger" aria-label={`Eliminar bloqueo del ${block.date}`} onClick={() => remove.mutate(block.id)}><Trash2 className="h-6 w-6" /></Button></Card>)}</div></section>
}

export function CatalogManagementPage() {
  const client = useQueryClient()
  const catalog = useQuery({ queryKey: ['admin-catalog'], queryFn: () => api<{ sections: { id: number; name: string }[]; procedures: { id: number; section: string; section_id: number; name: string; cost: number; duration: number; documents: string; active: boolean }[] }>('/citas/api/v1/catalog/') })
  const [section, setSection] = useState(''); const [name, setName] = useState(''); const [cost, setCost] = useState(''); const [duration, setDuration] = useState('15'); const [documents, setDocuments] = useState('')
  const mutation = useMutation({ mutationFn: (payload: unknown) => postJson('/citas/api/v1/catalog/', payload), onSuccess: () => { setName(''); setCost(''); setDocuments(''); client.invalidateQueries({ queryKey: ['admin-catalog'] }) } })
  function create(event: FormEvent) { event.preventDefault(); mutation.mutate({ action: 'create_procedure', section_id: section, name, cost, duration, documents }) }
  if (catalog.isLoading) return <LoadingState />
  return <section><p className="text-sm font-semibold text-primary">Configuración operativa</p><h1 className="mt-1 font-heading text-2xl font-semibold md:text-4xl">Catálogo de trámites</h1>{mutation.isError ? <Alert variant="error" className="mt-5">{mutation.error.message}</Alert> : null}<Card className="mt-8"><Landmark className="h-9 w-9 text-primary" /><CardTitle className="mt-4">Agregar trámite</CardTitle><form className="mt-5 grid gap-5 md:grid-cols-2" onSubmit={create}><Field label="Sección" htmlFor="catalog-section"><Select id="catalog-section" required value={section} onChange={(event) => setSection(event.target.value)}><option value="">Selecciona</option>{catalog.data?.sections.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</Select></Field><Field label="Nombre" htmlFor="catalog-name"><Input id="catalog-name" required value={name} onChange={(event) => setName(event.target.value)} /></Field><Field label="Costo" htmlFor="catalog-cost"><Input id="catalog-cost" required type="number" min="0" step="0.01" value={cost} onChange={(event) => setCost(event.target.value)} /></Field><Field label="Duración en minutos" htmlFor="catalog-duration"><Input id="catalog-duration" required type="number" min="5" value={duration} onChange={(event) => setDuration(event.target.value)} /></Field><div className="md:col-span-2"><Field label="Documentos requeridos" htmlFor="catalog-documents"><Textarea id="catalog-documents" value={documents} onChange={(event) => setDocuments(event.target.value)} /></Field></div><Button className="md:col-span-2" loading={mutation.isPending}><Plus className="h-6 w-6" />Agregar trámite</Button></form></Card><div className="mt-6 grid gap-4 lg:grid-cols-2">{catalog.data?.procedures.map((item) => <Card key={item.id} className={!item.active ? 'opacity-60' : ''}><BookOpenCheck className="h-7 w-7 text-primary" /><CardTitle className="mt-3">{item.name}</CardTitle><CardDescription>{item.section} · {formatMoney(item.cost)} · {item.duration} minutos</CardDescription><Button className="mt-4" variant="secondary" onClick={() => mutation.mutate({ action: 'toggle_procedure', procedure_id: item.id })}>{item.active ? 'Desactivar' : 'Activar'}</Button></Card>)}</div></section>
}
