# Generated by Django 6.0.5 on 2026-09-24 05:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('citas', '0006_cita_datos_adicionales'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversacionAsistente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=64, unique=True)),
                ('creado_el', models.DateTimeField(auto_now_add=True)),
                ('contexto', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Conversación del asistente',
                'verbose_name_plural': 'Conversaciones del asistente',
            },
        ),
        migrations.CreateModel(
            name='ReglaPrioridad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('palabras_clave', models.CharField(blank=True, help_text='Fragmento del nombre del trámite. Vacío aplica a todos.', max_length=200)),
                ('minutos_umbral', models.PositiveIntegerField(default=30)),
                ('estados', models.CharField(default='PENDIENTE', max_length=80)),
                ('solo_hoy', models.BooleanField(default=True)),
                ('accion_sugerida', models.CharField(default='Revisar solicitud.', max_length=200)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Regla de atención prioritaria',
                'verbose_name_plural': 'Reglas de atención prioritaria',
            },
        ),
        migrations.CreateModel(
            name='Anomalia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(blank=True, db_index=True, max_length=20)),
                ('clave', models.CharField(max_length=140, unique=True)),
                ('usuario_texto', models.CharField(blank=True, max_length=150)),
                ('area', models.CharField(default='Oficialía 03', max_length=80)),
                ('tipo', models.CharField(choices=[('ACTIVIDAD', 'Actividad fuera de patrón'), ('MODIFICACIONES', 'Modificaciones repetitivas'), ('ACCESO', 'Intentos de acceso'), ('HORARIO', 'Actividad fuera del horario habitual'), ('REGISTROS', 'Cambios inusuales en registros')], max_length=20)),
                ('descripcion', models.TextField()),
                ('evidencia', models.JSONField(blank=True, default=dict)),
                ('estado', models.CharField(default='DETECTADA', max_length=20)),
                ('clasificacion', models.CharField(blank=True, max_length=80)),
                ('detectada_el', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Anomalía',
                'verbose_name_plural': 'Anomalías',
                'ordering': ['-detectada_el'],
            },
        ),
        migrations.CreateModel(
            name='EventoInvestigacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(max_length=32)),
                ('nota', models.TextField(blank=True)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('anomalia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='ia.anomalia')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Evento de investigación',
                'verbose_name_plural': 'Bitácora de investigación de anomalías',
                'ordering': ['-fecha_hora'],
            },
        ),
        migrations.CreateModel(
            name='MensajeAsistente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(max_length=12)),
                ('texto', models.TextField()),
                ('metadatos', models.JSONField(blank=True, default=dict)),
                ('creado_el', models.DateTimeField(auto_now_add=True)),
                ('conversacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='ia.conversacionasistente')),
            ],
            options={
                'verbose_name': 'Mensaje del asistente',
                'verbose_name_plural': 'Mensajes del asistente',
                'ordering': ['creado_el', 'id'],
            },
        ),
        migrations.CreateModel(
            name='NotificacionInteligente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=140, unique=True)),
                ('destino', models.CharField(max_length=12)),
                ('curp', models.CharField(blank=True, db_index=True, max_length=18)),
                ('categoria', models.CharField(max_length=20)),
                ('titulo', models.CharField(max_length=180)),
                ('mensaje', models.TextField()),
                ('leida', models.BooleanField(default=False)),
                ('creado_el', models.DateTimeField(auto_now_add=True)),
                ('cita', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='citas.cita')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notificación inteligente',
                'verbose_name_plural': 'Notificaciones inteligentes',
                'ordering': ['-creado_el'],
            },
        ),
        migrations.CreateModel(
            name='PropuestaOptimizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('resumen', models.TextField()),
                ('analisis', models.JSONField(blank=True, default=dict)),
                ('movimientos', models.JSONField(blank=True, default=list)),
                ('estado', models.CharField(default='PROPUESTA', max_length=12)),
                ('creada_el', models.DateTimeField(auto_now_add=True)),
                ('revisada_el', models.DateTimeField(blank=True, null=True)),
                ('nota', models.TextField(blank=True)),
                ('revisada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='propuestas_ia_revisadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Propuesta de optimización',
                'verbose_name_plural': 'Propuestas de optimización',
                'ordering': ['-creada_el'],
            },
        ),
        migrations.CreateModel(
            name='AlertaUrgente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=80, unique=True)),
                ('titulo', models.CharField(max_length=200)),
                ('detalle', models.TextField(blank=True)),
                ('tiempo_minutos', models.PositiveIntegerField(default=0)),
                ('documentacion', models.CharField(default='completa', max_length=80)),
                ('accion_sugerida', models.CharField(max_length=200)),
                ('estado', models.CharField(default='ABIERTA', max_length=12)),
                ('creada_el', models.DateTimeField(auto_now_add=True)),
                ('revisada_el', models.DateTimeField(blank=True, null=True)),
                ('cita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas_ia', to='citas.cita')),
                ('revisada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('regla', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ia.reglaprioridad')),
            ],
            options={
                'verbose_name': 'Caso urgente',
                'verbose_name_plural': 'Casos urgentes',
                'ordering': ['-creada_el'],
            },
        ),
        migrations.CreateModel(
            name='SolicitudAtencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curp', models.CharField(blank=True, max_length=18)),
                ('nombre', models.CharField(blank=True, max_length=150)),
                ('motivo', models.TextField()),
                ('estado', models.CharField(default='PENDIENTE', max_length=20)),
                ('creado_el', models.DateTimeField(auto_now_add=True)),
                ('atendida_el', models.DateTimeField(blank=True, null=True)),
                ('atendida_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('conversacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ia.conversacionasistente')),
            ],
            options={
                'verbose_name': 'Solicitud de atención',
                'verbose_name_plural': 'Solicitudes de atención a funcionario',
                'ordering': ['-creado_el'],
            },
        ),
    ]
