# Generated by Django 6.0.5 on 2026-06-04 04:42

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SeccionTramite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True, verbose_name='Nombre de la Sección')),
            ],
            options={
                'verbose_name': 'Sección de Trámite',
                'verbose_name_plural': '📂 Secciones del Catálogo',
            },
        ),
        migrations.CreateModel(
            name='BitacoraAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('LOGIN', 'Inicio de Sesión'), ('ACCESO_DENEGADO', 'Intento de Acceso No Autorizado'), ('MODIFICACION_COSTO', 'Modificación de Tabulador Oficial'), ('MODIFICACION_CITA', 'Modificación de Cita'), ('CANCELACION_ERROR', 'Cancelación de Asistencia por Error'), ('CIERRE_CORTE', 'Cierre de Corte de Caja'), ('INFO', 'Informativo'), ('TRANSACCION', 'Movimiento Financiero'), ('SEGURIDAD', 'Alerta de Seguridad')], max_length=25, verbose_name='Acción Realizada')),
                ('descripcion', models.TextField(verbose_name='Descripción Detallada del Cambio')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora Exacta')),
                ('ip_direccion', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario Ejecutor')),
            ],
            options={
                'verbose_name': 'Registro de Auditoría',
                'verbose_name_plural': 'Bitácora de Auditoría (Logs)',
                'ordering': ['-fecha_hora'],
            },
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curp_ciudadano', models.CharField(max_length=18, validators=[django.core.validators.RegexValidator(message='La CURP debe tener exactamente 18 caracteres alfanuméricos.', regex='^[A-Z0-9]{18}$')], verbose_name='CURP')),
                ('nombre_ciudadano', models.CharField(max_length=150, verbose_name='Nombre Completo')),
                ('codigo_postal', models.CharField(max_length=5, validators=[django.core.validators.RegexValidator(message='El Código Postal debe ser de exactamente 5 números (ej. 50900).', regex='^[0-9]{5}$')], verbose_name='Código Postal')),
                ('direccion', models.TextField(verbose_name='Dirección Completa')),
                ('fecha', models.DateField(verbose_name='Fecha de la Cita')),
                ('hora', models.TimeField(verbose_name='Hora de la Cita')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ASISTIDA', 'Asistida en Ventanilla'), ('FINALIZADO', 'Finalizado (Pagado)'), ('CANCELADA', 'Cancelada')], default='PENDIENTE', max_length=15)),
                ('qr_codigo', models.CharField(default=uuid.uuid4, editable=False, help_text='Token único e infalsificable del código QR', max_length=64, unique=True)),
                ('creado_el', models.DateTimeField(auto_now_add=True)),
                ('codigo_qr', models.ImageField(blank=True, null=True, upload_to='qrs/')),
                ('usuario_atendio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Atendido por')),
            ],
            options={
                'verbose_name': 'Cita',
                'verbose_name_plural': 'Libreta de Citas (Agenda)',
            },
        ),
        migrations.CreateModel(
            name='PagoCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_cobrado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_pago', models.DateTimeField(default=django.utils.timezone.now)),
                ('corte_cierre_listo', models.BooleanField(default=False, verbose_name='Incluido en Corte de Caja')),
                ('cajero', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('cita', models.OneToOneField(limit_choices_to={'estado': 'ASISTIDA'}, on_delete=django.db.models.deletion.PROTECT, to='citas.cita')),
            ],
            options={
                'verbose_name': 'Registro de Pago',
                'verbose_name_plural': 'Caja Simultánea (Ingresos)',
            },
        ),
        migrations.CreateModel(
            name='Tramite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duracion_minutos', models.PositiveIntegerField(default=15, help_text='Duración estimada en minutos')),
                ('costo', models.DecimalField(decimal_places=2, help_text='Costo según tabulador oficial 2026', max_digits=10)),
                ('documentos_requeridos', models.TextField(blank=True, help_text='Papeles necesarios separados por comas o renglones', null=True)),
                ('activo', models.BooleanField(default=True, help_text='Desactivar en lugar de eliminar para proteger el historial')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Trámite')),
                ('seccion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tramites', to='citas.secciontramite', verbose_name='Sección')),
            ],
            options={
                'verbose_name': 'Trámite',
                'verbose_name_plural': 'Catálogo de Trámites',
                'unique_together': {('seccion', 'nombre')},
            },
        ),
        migrations.AddField(
            model_name='cita',
            name='tramite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='citas.tramite', verbose_name='Trámite a Realizar'),
        ),
    ]
