# Generated by Django 6.0.5 on 2026-06-30 03:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HorarioBloqueado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha bloqueada')),
                ('hora', models.TimeField(blank=True, null=True, verbose_name='Hora específica (vacío = todo el día)')),
                ('motivo', models.CharField(blank=True, max_length=200, verbose_name='Motivo del bloqueo')),
                ('creado_el', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Horario Bloqueado',
                'verbose_name_plural': 'Horarios Bloqueados',
                'ordering': ['fecha', 'hora'],
                'unique_together': {('fecha', 'hora')},
            },
        ),
    ]
