# Generated by Django 6.0.5 on 2026-07-02 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0002_horariobloqueado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ASISTIDA', 'Asistida en Ventanilla'), ('PAGADA', 'Pagada (Cobro Registrado)'), ('FINALIZADA', 'Finalizada (Trámite Completo)'), ('CANCELADA', 'Cancelada')], default='PENDIENTE', max_length=15),
        ),
    ]
